name: Deploy Portfolio

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Set environment dynamically
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}

    env:
      NODE_ENV: production
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.2

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}
          aws-region: ap-south-1

      - name: Build
        run: make all

      - name: Deploy
        run: make deploy
        env:
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
